### ISSUE TITLE
Unhandled exception. LibGit2Sharp.NotFoundException: object not found 

### ISSUE THREAD

**Issue by jeffrey-vang** [saintedlama/versionize#42]
LibGit2Sharp is throwing an exception when versionize is being used inside of a github action. This one of the few tools I have found that does both changelog generation and semantic versioning for .NET projects. It would be nice to automate this process from a Github Action. Any guidance on how to do this?

## Exception
Unhandled exception. LibGit2Sharp.NotFoundException: object not found - no match for id (37f07590b932411758c6af8b3272d0d206386c1b)

## Workflow
```
name: Version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - run: dotnet tool install --global Versionize
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.head.ref }}
      - name: Version
        run: versionize
      - name: Push Updates
        run: git push --follow-tags origin test-master

```
